[build-system]
requires = ["setuptools >= 64"]
build-backend = "setuptools.build_meta"

[project]
name = "sklearn-nature-inspired-algorithms"
version = "0.13.0"
description = "Search using nature inspired algorithms over specified parameter values for an sklearn estimator."
license = "MIT"
readme = "README.md"
requires-python = ">= 3.9"
authors = [
    { name = "Timotej Zatko", email = "timi.zatko@gmail.com" },
]
keywords = ["sklearn", "scikit-learn", "nature-inspired-algorithms", "hyper-parameter-tuning"]

dependencies = [
    "scikit-learn >= 1.0.2",
    "numpy >= 1.22",
    "matplotlib >= 3.5",
    "seaborn >= 0.11",
    "pandas >= 1.4",
    "niapy >= 2.0",
    "scipy >= 1.7.3",
]

[project.optional-dependencies]
dev = [
    "flake8 >= 6.0",
    "coverage >= 7.0",
    "build",
]

[project.urls]
Homepage = "https://github.com/timzatko/Sklearn-Nature-Inspired-Algorithms"
Repository = "https://github.com/timzatko/Sklearn-Nature-Inspired-Algorithms"

[tool.setuptools.packages.find]
include = ["sklearn_nature_inspired_algorithms*"]
